import os
import logging
from google import genai
from google.genai import types
from pydantic import BaseModel, Field
from typing import List, Dict, Any

logger = logging.getLogger(__name__)

def get_gemini_client():
    api_key = os.getenv("GEMINI_API_KEY")
    return genai.Client(api_key=api_key) if api_key else None

class ClaimVerification(BaseModel):
    claim: str = Field(description="A distinct factual claim extracted from the query.")
    verdict: str = Field(description="Strictly one of: 'True', 'False', or 'Unverified'.")
    explanation: str = Field(description="A brief explanation for the verdict based entirely on the provided evidence.")

class GlobalVerificationResponse(BaseModel):
    claims: List[ClaimVerification]
    score: float = Field(description="An overall truth score ranging from 0.0 (Completely False) to 1.0 (Completely True).")
    explanation: str = Field(description="A master explanation summarizing the overall finding.")

async def verify_all_claims(query: str, evidence_text: str) -> Dict[str, Any]:
    """
    Takes the user query and ALL scrape evidence.
    Asks Gemini to extract claims, verify them, score them, and explain, returning a structured JSON object.
    Requires EXACTLY ONE API CALL.
    """
    logger.info(f"Initiating single-pass Gemini verification for query: {query}")
    client = get_gemini_client()
    if not client:
        logger.warning("No GEMINI_API_KEY found, returning mock verification payload.")
        return {
            "score": 0.5,
            "verdict": "Unverified",
            "claims": [{"claim": "Mock claim", "verdict": "Unverified", "explanation": "No API key."}],
            "explanation": "No LLM API configured. Mock result."
        }

    prompt = f"""
    You are an expert fact-checking AI. A user has provided a query/headline. We have scraped the web for context.
    
    User Query: '{query}'
    
    Evidence Context (Scraped from Trusted Sources):
    {evidence_text}
    
    INSTRUCTIONS:
    1. Extract the core factual claims from the User Query.
    2. Determine if each claim is True, False, or Unverified based EXCLUSIVELY on the Evidence Context.
    3. Generate a final confidence/truth score out of 1.0.
    4. Write a concise overall explanation.
    """

    try:
        logger.info("Calling Gemini 2.5 Flash for unified generation...")
        response = await client.aio.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=0.0,
                response_mime_type="application/json",
                response_schema=GlobalVerificationResponse,
            )
        )
        
        # Parse the structured Pydantic response generated by the SDK
        result: GlobalVerificationResponse = response.parsed
        logger.info(f"Unified verification successful. Extracted {len(result.claims)} claims with score {result.score}.")
        
        # Calculate overall categorical verdict
        if result.score > 0.7: global_verdict = "True"
        elif result.score < 0.4: global_verdict = "False"
        else: global_verdict = "Unverified"
        
        return {
            "verdict": global_verdict,
            "score": result.score,
            "claims": [c.model_dump() for c in result.claims],
            "explanation": result.explanation
        }
        
    except Exception as e:
        logger.error(f"Error during unified Gemini verification: {e}", exc_info=True)
        return {
            "verdict": "Unverified",
            "score": 0.0,
            "claims": [],
            "explanation": "Failed to complete unified verification due to an API error."
        }
